DROP TABLE COMPETICIONES CASCADE CONSTRAINTS;
CREATE TABLE COMPETICIONES (
    ID_COMPETICION NUMBER(4)GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    ESTADO VARCHAR(20) CONSTRAINT com_est_ck CHECK(ESTADO IN('inscripcion', 'en curso', 'finalizada'))
);

DROP TABLE JORNADAS CASCADE CONSTRAINTS;
CREATE TABLE JORNADAS (
    ID_JORNADA NUMBER(4) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FECHA DATE,
    ID_COMPETICION NUMBER(4),
    CONSTRAINT jor_com_fk FOREIGN KEY (ID_COMPETICION) REFERENCES COMPETICIONES(ID_COMPETICION)
    ON DELETE CASCADE
);

DROP TABLE EQUIPOS CASCADE CONSTRAINTS;
CREATE TABLE EQUIPOS (
    ID_EQUIPO NUMBER(4) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(20)NOT NULL UNIQUE,
    FECHA_FUND DATE
);

DROP TABLE JUGADORES CASCADE CONSTRAINTS;
CREATE TABLE JUGADORES (
    ID_JUGADOR NUMBER(4) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(20)NOT NULL,
    APELLIDO VARCHAR2(30),
    NACIONALIDAD VARCHAR2(30),
    FECHA_NAC DATE,
    NICKNAME VARCHAR2(20) UNIQUE,
    SUELDO NUMBER(5),
    ID_EQUIPO NUMBER(4),
    CONSTRAINT jug_equ_fk FOREIGN KEY(ID_EQUIPO) REFERENCES EQUIPOS(ID_EQUIPO)
    ON DELETE CASCADE
);

DROP TABLE ENFRENTAMIENTOS CASCADE CONSTRAINTS;
CREATE TABLE ENFRENTAMIENTOS (
    ID_ENFRENTAMIENTO NUMBER(4) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HORA DATE NOT NULL,
    FECHA_ENF DATE NOT NULL,
    EQUIPO_ATACANTE NUMBER(4),
    EQUIPO_DEFENSOR NUMBER(4),
    EQUIPO_GANADOR NUMBER(4),
    ID_JORNADA NUMBER(4),
    CONSTRAINT enf_atc_fk FOREIGN KEY (EQUIPO_ATACANTE) REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT enf_def_fk FOREIGN KEY (EQUIPO_DEFENSOR) REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT enf_gan_fk FOREIGN KEY (EQUIPO_GANADOR) REFERENCES EQUIPOS(ID_EQUIPO),
    CONSTRAINT enf_jor_fk FOREIGN KEY (ID_JORNADA) REFERENCES JORNADAS(ID_JORNADA)
);

DROP TABLE USUARIOS CASCADE CONSTRAINTS;
CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER(4) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NICKNAME VARCHAR2(30) NOT NULL UNIQUE,
    CLAVE VARCHAR2(4) NOT NULL, 
    TIPO_USUARIO VARCHAR2(30) NOT NULL,
    CONSTRAINT CHK_TIPO_USUARIO CHECK (TIPO_USUARIO IN ('admin', 'user'))
);
